# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/clothing_store.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotos/clothing_store.proto\x12\rClothingStore\"\'\n\x14\x41rticleSearchRequest\x12\x0f\n\x07\x62\x61rcode\x18\x01 \x01(\t\"S\n\x05Offer\x12\x18\n\x10\x64iscount_percent\x18\x01 \x01(\x02\x12\x14\n\x0cmax_discoutn\x18\x02 \x01(\x02\x12\x1a\n\x12min_original_price\x18\x03 \x01(\x02\"\x9f\x01\n\x15\x41rticleSearchResponse\x12\x11\n\titem_type\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\t\x12\x0e\n\x06\x63olour\x18\x03 \x01(\t\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\r\n\x05price\x18\x06 \x01(\x02\x12$\n\x06offers\x18\x07 \x03(\x0b\x32\x14.ClothingStore.Offer2s\n\rClothingStore\x12\x62\n\x13GetArticleByBarcode\x12#.ClothingStore.ArticleSearchRequest\x1a$.ClothingStore.ArticleSearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.clothing_store_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ARTICLESEARCHREQUEST']._serialized_start=46
  _globals['_ARTICLESEARCHREQUEST']._serialized_end=85
  _globals['_OFFER']._serialized_start=87
  _globals['_OFFER']._serialized_end=170
  _globals['_ARTICLESEARCHRESPONSE']._serialized_start=173
  _globals['_ARTICLESEARCHRESPONSE']._serialized_end=332
  _globals['_CLOTHINGSTORE']._serialized_start=334
  _globals['_CLOTHINGSTORE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
